name: r-blis
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::libblas=*=*_blis
  - conda-forge::r-base
  - conda-forge::r-xml2
  - conda-forge::r-openssl
  - conda-forge::r-git2r
